apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: hpdc-alerts-dev

namePrefix: dev-
labels:
  - includeExpressions:
      namespace: hpdc-alerts-dev
      app.kubernetes.io/part-of: hpdc-platform