apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    app.kubernetes.io/name: security
    app.kubernetes.io/part-of: hpdc-platform

---
apiVersion: v1
kind: Secret
metadata:
  name: events-api-key
  namespace: security
  labels:
    app.kubernetes.io/name: events-api-key
    app.kubernetes.io/part-of: hpdc-platform
type: Opaque
stringData:
  events-key: hpdc-events-dev-key

---
apiVersion: v1
kind: Secret
metadata:
  name: telemetry-api-key
  namespace: security
  labels:
    app.kubernetes.io/name: telemetry-api-key
    app.kubernetes.io/part-of: hpdc-platform
type: Opaque
stringData:
  telemetry-key: hpdc-telemetry-dev-key

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: hpdc-messaging-api-key-authn
  namespace: envoy-gateway-system
  labels:
    app.kubernetes.io/name: hpdc-messaging-api-key-authn
    app.kubernetes.io/part-of: hpdc-platform
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: hpdc-edge-domain-routes
  apiKeyAuth:
    credentialRefs:
      - group: ""
        kind: Secret
        name: events-api-key
        namespace: security
    extractFrom:
      - headers:
          - X-API-Key

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: hpdc-telemetry-grpc-api-key-authn
  namespace: telemetry-ingestion
  labels:
    app.kubernetes.io/name: hpdc-telemetry-grpc-api-key-authn
    app.kubernetes.io/part-of: hpdc-platform
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: GRPCRoute
    name: hpdc-telemetry-grpc-ingestion
  apiKeyAuth:
    credentialRefs:
      - group: ""
        kind: Secret
        name: telemetry-api-key
        namespace: security
    extractFrom:
      - headers:
          - X-API-Key