apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: hpdc-telemetry-http-api-key-authn
  namespace: telemetry-ingestion
  labels:
    app.kubernetes.io/name: hpdc-telemetry-http-api-key-authn
    app.kubernetes.io/part-of: hpdc-platform
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: hpdc-telemetry-http-ingestion
  apiKeyAuth:
    credentialRefs:
      - group: ""
        kind: Secret
        name: telemetry-api-key
        namespace: security
    extractFrom:
      - headers:
          - X-API-Key