apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/api-key-authn.yaml
  - ../../base/graphql-gateway-authn.yaml
  - ../../base/telemetry-http-api-key-authn.yaml
