apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/entity-store.yaml
  - ../../base/entity-crud.yaml
  - ../../base/entity-change-feed.yaml
namespace: entity-store
commonLabels:
  environment: dev
