apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/standalone.yaml
  - ../../base/operator.yaml
  - ../../base/network-policy.yaml
namespace: pulsar
commonLabels:
  environment: dev