#!/usr/bin/env python3
"""Validate the Talos dev bootstrap scaffold."""

from pathlib import Path
import re
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS_DIR = ROOT / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))
REQUIRED_FILES = [
    ROOT / "startup.dev.py",
    ROOT / "scripts" / "steps" / "02-bootstrap-talos-dev.py",
    ROOT / "platform" / "talos" / "machine-config.yaml",
    ROOT / "docs" / "bootstrap.md",
    ROOT / "docs" / "talos-dev-cluster.md",
    ROOT / "tests" / "test_bootstrap_dev.py",
    ROOT / "tests" / "test_bootstrap_talos_dev.py",
]


def main() -> int:
    failures = []
    for path in REQUIRED_FILES:
        if not path.exists():
            failures.append(f"missing file: {path.relative_to(ROOT)}")
    if failures:
        print("Talos bootstrap scaffold validation failed:")
        for failure in failures:
            print(f"- {failure}")
        return 1
    print("Talos bootstrap scaffold validation passed.")
    return 0


def test_configure_talosconfig_ignores_unreadable_existing_config() -> None:
    import unittest.mock
    import bootstrap_talos_dev as module

    with tempfile.TemporaryDirectory() as tmp:
        talosconfig = Path(tmp) / "talosconfig"
        talosconfig.write_text("real config bytes\n", encoding="utf-8")
        original = module.TALOSCONFIG
        module.TALOSCONFIG = talosconfig
        try:
            with unittest.mock.patch.object(Path, "read_text", side_effect=PermissionError("permission denied")):
                module.configure_talosconfig()
        finally:
            module.TALOSCONFIG = original
        assert talosconfig.exists(), "unreadable existing talosconfig must be left untouched"
        assert talosconfig.read_text(encoding="utf-8") == "real config bytes\n", "existing talosconfig content must be preserved"


def test_configure_talosconfig_removes_placeholder_marker() -> None:
    import bootstrap_talos_dev as module

    with tempfile.TemporaryDirectory() as tmp:
        talosconfig = Path(tmp) / "talosconfig"
        talosconfig.write_text("# Local Talos administrative config is generated by talosctl kubeconfig.\n", encoding="utf-8")
        original = module.TALOSCONFIG
        module.TALOSCONFIG = talosconfig
        try:
            module.configure_talosconfig()
        finally:
            module.TALOSCONFIG = original
        assert not talosconfig.exists(), "stale placeholder marker must be removed"


def test_configure_talosconfig_creates_placeholder_when_missing() -> None:
    import bootstrap_talos_dev as module

    with tempfile.TemporaryDirectory() as tmp:
        talosconfig = Path(tmp) / "talosconfig"
        original = module.TALOSCONFIG
        module.TALOSCONFIG = talosconfig
        try:
            module.configure_talosconfig()
        finally:
            module.TALOSCONFIG = original
        assert talosconfig.exists(), "missing talosconfig must be seeded with a placeholder"


if __name__ == "__main__":
    sys.exit(main())
