apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/regional-hub.yaml
namespace: regional-hub
commonLabels:
  app.kubernetes.io/name: hpdc-regional-hub
  app.kubernetes.io/component: multi-region
  app.kubernetes.io/part-of: hpdc-platform
