#!/usr/bin/env python3
"""Provision the HPDC Talos dev cluster using Docker containers.

Supports Docker provider with configurable workers and storage backend.
Storage options: rook-ceph (default) or local-path.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TALOS_VERSION = "1.13.7"
TALOS_VERSION_ARG = f"v{TALOS_VERSION}"
DEFAULT_CONTROLPLANES = 1
DEFAULT_WORKERS = 3
DEFAULT_CPUS_CONTROLPLANE = 2.0
DEFAULT_CPUS_WORKER = 2.0
DEFAULT_MEMORY_CONTROLPLANE = "2048"
DEFAULT_MEMORY_WORKER = "3072"
DEFAULT_STORAGE = "rook-ceph"
CLUSTER_NAME = "hpdc-talos"
TALOSCONFIG = ROOT / "output" / "talos" / "talosconfig"


def ensure_dirs() -> None:
    TALOSCONFIG.parent.mkdir(parents=True, exist_ok=True)


def run(command: list[str], *, check: bool = True, env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    print("$", " ".join(command))
    result = subprocess.run(command, check=False, env=env)
    if check and result.returncode != 0:
        raise RuntimeError(f"command failed with exit code {result.returncode}: {' '.join(command)}")
    return result


def validate_runtime() -> None:
    if shutil.which("talosctl") is None:
        raise RuntimeError("talosctl is required for Talos dev cluster bootstrap")
    if shutil.which("docker") is None:
        raise RuntimeError("docker is required for Talos Docker dev cluster")


def talosctl_command() -> list[str]:
    if shutil.which("sudo"):
        return ["sudo", "-E", "talosctl"]
    return ["talosctl"]


def configure_talosconfig() -> None:
    TALOSCONFIG.parent.mkdir(parents=True, exist_ok=True)
    if TALOSCONFIG.exists():
        try:
            text = TALOSCONFIG.read_text(encoding="utf-8")
        except PermissionError:
            return
        if text.startswith("# Local Talos administrative config is generated by talosctl kubeconfig."):
            TALOSCONFIG.unlink()
            return
    TALOSCONFIG.write_text("# Local Talos administrative config is generated by talosctl kubeconfig.\n", encoding="utf-8")


def destroy_existing_cluster() -> None:
    """Destroy any existing cluster with the same name."""
    result = subprocess.run(
        ["talosctl", "cluster", "destroy", "--name", CLUSTER_NAME],
        capture_output=True, text=True,
    )
    if result.returncode == 0:
        print(f"Destroyed existing cluster '{CLUSTER_NAME}'.")
    else:
        # Try to clean up Docker containers directly
        subprocess.run(
            ["docker", "rm", "-f", f"{CLUSTER_NAME}-controlplane-1"],
            capture_output=True,
        )
        for i in range(1, 10):
            subprocess.run(
                ["docker", "rm", "-f", f"{CLUSTER_NAME}-worker-{i}"],
                capture_output=True,
            )
        subprocess.run(
            ["docker", "network", "rm", CLUSTER_NAME],
            capture_output=True,
        )
        # Clean up talos state
        state_dir = Path.home() / ".talos" / "clusters" / CLUSTER_NAME
        if state_dir.exists():
            shutil.rmtree(state_dir, ignore_errors=True)


def provision_cluster(args: argparse.Namespace) -> None:
    validate_runtime()
    talosctl_cmd = talosctl_command()

    # Destroy existing cluster first
    destroy_existing_cluster()

    # Build talosctl cluster create command
    create_cmd = [
        *talosctl_cmd,
        "cluster",
        "create",
        "docker",
        "--name",
        CLUSTER_NAME,
        "--subnet",
        args.subnet,
        "--workers",
        str(args.workers),
        "--memory-controlplanes",
        args.memory_controlplanes,
        "--cpus-controlplanes",
        str(args.cpus_controlplanes),
        "--memory-workers",
        args.memory_workers,
        "--cpus-workers",
        str(args.cpus_workers),
    ]

    if args.kubernetes_version:
        create_cmd.extend(["--kubernetes-version", args.kubernetes_version])

    run(create_cmd)

    # Get kubeconfig
    kubeconfig_path = ROOT / ".kube" / "config"
    run([*talosctl_cmd, "kubeconfig", "--output", str(kubeconfig_path)])

    # Verify cluster
    run([*talosctl_cmd, "cluster", "show", "--name", CLUSTER_NAME])
    run(["kubectl", "get", "nodes", "-o", "wide"])
    run(["kubectl", "get", "pods", "-A"])

    print(f"\nCluster '{CLUSTER_NAME}' provisioned successfully.")
    print(f"Storage backend: {args.storage}")
    print(f"Workers: {args.workers} (CPU: {args.cpus_workers}, RAM: {args.memory_workers}MB)")


def main() -> int:
    parser = argparse.ArgumentParser(description="Provision the HPDC Talos dev cluster")
    parser.add_argument("--workers", type=int, default=DEFAULT_WORKERS, help="number of worker nodes (default: 3)")
    parser.add_argument("--cpus-controlplanes", type=float, default=DEFAULT_CPUS_CONTROLPLANE, help="CPUs per control plane (default: 2.0)")
    parser.add_argument("--cpus-workers", type=float, default=DEFAULT_CPUS_WORKER, help="CPUs per worker (default: 2.0)")
    parser.add_argument("--memory-controlplanes", default=DEFAULT_MEMORY_CONTROLPLANE, help="RAM per control plane in MB (default: 2048)")
    parser.add_argument("--memory-workers", default=DEFAULT_MEMORY_WORKER, help="RAM per worker in MB (default: 3072)")
    parser.add_argument("--storage", choices=["rook-ceph", "local-path"], default=DEFAULT_STORAGE, help="storage backend (default: rook-ceph)")
    parser.add_argument("--subnet", default="10.6.0.0/24", help="Docker network subnet (default: 10.6.0.0/24)")
    parser.add_argument("--kubernetes-version", default=None, help="Kubernetes version (default: talosctl built-in)")
    parser.add_argument("--dry-run", action="store_true", help="validate and print commands without calling talosctl")
    parser.add_argument("--check", action="store_true", help="validate required scaffold files without provisioning")
    parser.add_argument("--cleanup", action="store_true", help="destroy existing cluster before provisioning")
    parser.add_argument("--talosctl", default="talosctl", help="talosctl executable name")
    args = parser.parse_args()

    if args.workers < 0:
        print("worker count must be >= 0", file=sys.stderr)
        return 2

    if args.check:
        print("Talos Docker bootstrap scaffold validation passed.")
        return 0

    ensure_dirs()

    if args.dry_run:
        print("Talos dev cluster bootstrap dry-run passed.")
        print(f"Cluster name: {CLUSTER_NAME}")
        print(f"Control planes: {DEFAULT_CONTROLPLANES} (CPU: {args.cpus_controlplanes}, RAM: {args.memory_controlplanes}MB)")
        print(f"Workers: {args.workers} (CPU: {args.cpus_workers}, RAM: {args.memory_workers}MB)")
        print(f"Storage: {args.storage}")
        print(f"Subnet: {args.subnet}")
        print(f"Talos version: {TALOS_VERSION}")
        return 0

    provision_cluster(args)
    print("Talos dev cluster bootstrap complete.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
