apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alert-audit-trail.yaml
  - alert-handler-actions.yaml
  - alert-handler-api.yaml
  - alert-response-engine.yaml
  - alert-response-function.yaml
  - alert-workflows.yaml
  - llm-decision-support.yaml
  - llm-decision-support-api.yaml
