#!/usr/bin/env python3
"""Provision the HPDC Talos dev cluster using persistent QEMU disk images."""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TALOS_VERSION = "1.13.7"
TALOS_VERSION_ARG = f"v{TALOS_VERSION}"
DEFAULT_NODE_COUNT = 1
NODE_BASE = 11
DISK_DIR = ROOT / "output" / "qemu"
TALOSCONFIG = ROOT / "output" / "talos" / "talosconfig"
NODE_SPECS = ROOT / "output" / "talos" / "node-specs.yaml"
TALOS_IMAGE = ROOT / "output" / "qemu" / "images" / f"talos-v{TALOS_VERSION}.iso"
DISK_SIZE = "16G"


def disk_path(index: int) -> Path:
    return DISK_DIR / f"talos-v{index}.img"


def ensure_dirs() -> None:
    for directory in (DISK_DIR, TALOSCONFIG.parent, NODE_SPECS.parent):
        directory.mkdir(parents=True, exist_ok=True)


def cleanup_disks(node_count: int) -> None:
    for index in range(1, node_count + 1):
        path = disk_path(index)
        if path.exists():
            path.unlink()


def create_disk_image(path: Path, size: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        return
    qemu_img = shutil.which("qemu-img")
    if qemu_img:
        run([qemu_img, "create", "-f", "qcow2", str(path), size], check=False)
        if not path.exists() or path.stat().st_size == 0:
            raise RuntimeError(f"qemu-img failed to create persistent disk {path}")
        return
    with path.open("wb") as handle:
        handle.truncate(path.stat().st_size if path.exists() else 0)
    with path.open("r+b") as handle:
        handle.truncate(size_to_bytes(size))


def size_to_bytes(size: str) -> int:
    suffixes = {"K": 1024, "M": 1024**2, "G": 1024**3}
    number = "".join(ch for ch in size if ch.isdigit())
    suffix = "".join(ch for ch in size if not ch.isdigit())
    return int(number) * suffixes[suffix.upper()]


def generate_node_specs(node_count: int) -> None:
    lines = [
        "nodes:",
    ]
    for index in range(1, node_count + 1):
        address_octet = NODE_BASE + index - 1
        lines.extend(
            [
                f"  - address: 192.168.100.{address_octet}",
                "    machineOS: talos",
                "    machineInstall:",
                f"      image: talos:v{TALOS_VERSION}",
                "      disk: /dev/vda",
                "      extraKernelArgs:",
                "        - talos.platform=metal",
            ]
        )
    NODE_SPECS.write_text("\n".join(lines) + "\n", encoding="utf-8")


def run(command: list[str], *, check: bool = True, env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    print("$", " ".join(command))
    result = subprocess.run(command, check=False, env=env)
    if check and result.returncode != 0:
        raise RuntimeError(f"command failed with exit code {result.returncode}: {' '.join(command)}")
    return result


def validate_runtime() -> None:
    if shutil.which("talosctl") is None:
        raise RuntimeError("talosctl is required for Talos dev cluster bootstrap")
    if TALOS_IMAGE.exists():
        return
    raise RuntimeError(
        "Talos offline image not found. Pre-cache the Talos installer image before running offline bootstrap: "
        f"{TALOS_IMAGE}"
    )


def talosctl_command(args: argparse.Namespace) -> list[str]:
    if args.talosctl == "talosctl" and shutil.which("sudo"):
        return ["sudo", "-E", "talosctl"]
    return [args.talosctl]


def configure_talosconfig() -> None:
    TALOSCONFIG.parent.mkdir(parents=True, exist_ok=True)
    if TALOSCONFIG.exists():
        text = TALOSCONFIG.read_text(encoding="utf-8")
        if text.startswith("# Local Talos administrative config is generated by talosctl kubeconfig."):
            TALOSCONFIG.unlink()
        return
    TALOSCONFIG.write_text("# Local Talos administrative config is generated by talosctl kubeconfig.\n", encoding="utf-8")


def provision_cluster(args: argparse.Namespace) -> None:
    validate_runtime()
    talosctl_cmd = talosctl_command(args)
    if shutil.which(talosctl_cmd[-1]) is None:
        raise RuntimeError(f"talosctl executable not found: {talosctl_cmd[-1]}")

    env = os.environ.copy()
    env["TALOSCTL_OFFLINE_MODE"] = "1"

    run(
        [
            *talosctl_cmd,
            "cluster",
            "create",
            "qemu",
            "--presets",
            "iso",
            "--talos-version",
            args.talos_version,
            "--talosconfig-destination",
            str(TALOSCONFIG),
            "--state",
            str(DISK_DIR),
            "--controlplanes",
            "1",
            "--workers",
            "0",
            "--disks",
            f"virtio:{DISK_SIZE}",
            "--name",
            "hpdc-talos",
        ],
        env=env,
    )
    run([*talosctl_cmd, "kubeconfig", "--output", str(TALOSCONFIG)], env=env)
    run([*talosctl_cmd, "health"], env=env)
    run([*talosctl_cmd, "get", "nodes"], env=env)
    run([*talosctl_cmd, "get", "disks"], env=env)


def check_scaffold() -> list[str]:
    failures = []
    required = [
        ROOT / "startup.dev.py",
        ROOT / "scripts" / "steps" / "02-bootstrap-talos-dev.py",
        ROOT / "docs" / "bootstrap.md",
        ROOT / "tests" / "test_bootstrap_talos_dev.py",
    ]
    for path in required:
        if not path.exists():
            failures.append(str(path.relative_to(ROOT)))
    return failures


def main() -> int:
    parser = argparse.ArgumentParser(description="Provision the HPDC Talos dev cluster")
    parser.add_argument("--nodes", type=int, default=DEFAULT_NODE_COUNT, help="number of Talos VMs to provision")
    parser.add_argument("--talos-version", default=TALOS_VERSION_ARG, help="Talos version to bootstrap")
    parser.add_argument("--offline", action="store_true", default=True, help="require offline artifacts")
    parser.add_argument("--cleanup", action="store_true", help="remove existing persistent QEMU disk images before provisioning")
    parser.add_argument("--dry-run", action="store_true", help="validate and print commands without calling talosctl")
    parser.add_argument("--check", action="store_true", help="validate required scaffold files without provisioning")
    parser.add_argument("--talosctl", default="talosctl", help="talosctl executable name")
    args = parser.parse_args()

    if args.nodes < 1:
        print("node count must be at least 1", file=sys.stderr)
        return 2

    if args.check:
        failures = check_scaffold()
        if failures:
            print("Talos bootstrap scaffold validation failed:")
            for failure in failures:
                print(f"- {failure}")
            return 1
        print("Talos bootstrap scaffold validation passed.")
        return 0

    ensure_dirs()
    if args.cleanup:
        cleanup_disks(args.nodes)
    for index in range(1, args.nodes + 1):
        create_disk_image(disk_path(index), DISK_SIZE)
    generate_node_specs(args.nodes)
    configure_talosconfig()

    if args.dry_run:
        print("Talos dev cluster bootstrap dry-run passed.")
        print(f"Persistent QEMU disks: {[str(path.relative_to(ROOT)) for path in (disk_path(i) for i in range(1, args.nodes + 1))]}")
        print(f"Talos version: {args.talos_version}")
        print(f"Node specs: {NODE_SPECS.relative_to(ROOT)}")
        print(f"talosconfig: {TALOSCONFIG.relative_to(ROOT)}")
        return 0

    provision_cluster(args)
    print("Talos dev cluster bootstrap complete.")
    print(f"talosconfig: {TALOSCONFIG.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
