apiVersion: v1
entries:
  cert-manager:
  - annotations:
      artifacthub.io/category: security
      artifacthub.io/license: Apache-2.0
      artifacthub.io/prerelease: "false"
      artifacthub.io/signKey: |
        fingerprint: 1020CF3C033D4F35BAE1C19E1226061C665DF13E
        url: https://cert-manager.io/public-keys/cert-manager-keyring-2021-09-20-1020CF3C033D4F35BAE1C19E1226061C665DF13E.gpg
    apiVersion: v2
    appVersion: v1.21.1
    created: "2026-09-01T00:39:07.856962509+03:00"
    description: A Helm chart for cert-manager
    digest: c27101f3f3e2349fb4a9e704316105bf7b52ad73b8c8257d3498ef7f2f6a4adc
    home: https://cert-manager.io
    icon: https://raw.githubusercontent.com/cert-manager/community/4d35a69437d21b76322157e6284be4cd64e6d2b7/logo/logo-small.png
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    kubeVersion: '>= 1.22.0-0'
    maintainers:
    - email: cert-manager-maintainers@googlegroups.com
      name: cert-manager-maintainers
      url: https://cert-manager.io
    name: cert-manager
    sources:
    - https://github.com/cert-manager/cert-manager
    urls:
    - http://10.6.0.1:8080/cert-manager-v1.21.1.tgz
    version: v1.21.1
  cilium:
  - annotations:
      artifacthub.io/crds: "- kind: CiliumNetworkPolicy\n  version: v2\n  name: ciliumnetworkpolicies.cilium.io\n
        \ displayName: Cilium Network Policy\n  description: |\n    Cilium Network
        Policies provide additional functionality beyond what\n    is provided by
        standard Kubernetes NetworkPolicy such as the ability\n    to allow traffic
        based on FQDNs, or to filter at Layer 7.\n- kind: CiliumClusterwideNetworkPolicy\n
        \ version: v2\n  name: ciliumclusterwidenetworkpolicies.cilium.io\n  displayName:
        Cilium Clusterwide Network Policy\n  description: |\n    Cilium Clusterwide
        Network Policies support configuring network traffic\n    policiies across
        the entire cluster, including applying node firewalls.\n- kind: CiliumLocalRedirectPolicy\n
        \ version: v2\n  name: ciliumlocalredirectpolicies.cilium.io\n  displayName:
        Cilium Local Redirect Policy\n  description: |\n    Cilium Local Redirect
        Policy allows local redirects to be configured\n    within a node to support
        use cases like Node-Local DNS.\n- kind: CiliumNode\n  version: v2\n  name:
        ciliumnodes.cilium.io\n  displayName: Cilium Node\n  description: |\n    Cilium
        Node represents a node managed by Cilium. It contains a\n    specification
        to control various node specific configuration aspects\n    and a status section
        to represent the status of the node.\n- kind: CiliumIdentity\n  version: v2\n
        \ name: ciliumidentities.cilium.io\n  displayName: Cilium Identity\n  description:
        |\n    Cilium Identity allows introspection into security identities that\n
        \   Cilium allocates which identify sets of labels that are assigned to\n
        \   individual endpoints in the cluster.\n- kind: CiliumEndpoint\n  version:
        v2\n  name: ciliumendpoints.cilium.io\n  displayName: Cilium Endpoint\n  description:
        |\n    Cilium Endpoint represents the status of individual pods or nodes in\n
        \   the cluster which are managed by Cilium, including enforcement status,\n
        \   IP addressing and whether the networking is successfully operational.\n-
        kind: CiliumEndpointSlice\n  version: v2alpha1\n  name: ciliumendpointslices.cilium.io\n
        \ displayName: Cilium Endpoint Slice\n  description: |\n    Cilium Endpoint
        Slice represents the status of groups of pods or nodes\n    in the cluster
        which are managed by Cilium, including enforcement status,\n    IP addressing
        and whether the networking is successfully operational.\n- kind: CiliumEgressGatewayPolicy\n
        \ version: v2\n  name: ciliumegressgatewaypolicies.cilium.io\n  displayName:
        Cilium Egress Gateway Policy\n  description: |\n    Cilium Egress Gateway
        Policy provides control over the way that traffic\n    leaves the cluster
        and which source addresses to use for that traffic.\n- kind: CiliumClusterwideEnvoyConfig\n
        \ version: v2\n  name: ciliumclusterwideenvoyconfigs.cilium.io\n  displayName:
        Cilium Clusterwide Envoy Config\n  description: |\n    Cilium Clusterwide
        Envoy Config specifies Envoy resources and K8s service mappings\n    to be
        provisioned into Cilium host proxy instances in cluster context.\n- kind:
        CiliumEnvoyConfig\n  version: v2\n  name: ciliumenvoyconfigs.cilium.io\n  displayName:
        Cilium Envoy Config\n  description: |\n    Cilium Envoy Config specifies Envoy
        resources and K8s service mappings\n    to be provisioned into Cilium host
        proxy instances in namespace context.\n- kind: CiliumNodeConfig\n  version:
        v2\n  name: ciliumnodeconfigs.cilium.io\n  displayName: Cilium Node Configuration\n
        \ description: |\n    CiliumNodeConfig is a list of configuration key-value
        pairs. It is applied to\n    nodes indicated by a label selector.\n- kind:
        CiliumBGPClusterConfig\n  version: v2alpha1\n  name: ciliumbgpclusterconfigs.cilium.io\n
        \ displayName: Cilium BGP Cluster Config\n  description: |\n    Cilium BGP
        Cluster Config instructs Cilium operator to create specific BGP cluster\n
        \   configurations.\n- kind: CiliumBGPPeerConfig\n  version: v2alpha1\n  name:
        ciliumbgppeerconfigs.cilium.io\n  displayName: Cilium BGP Peer Config\n  description:
        |\n    CiliumBGPPeerConfig is a common set of BGP peer configurations. It
        can be referenced \n    by multiple peers from CiliumBGPClusterConfig.\n-
        kind: CiliumBGPAdvertisement\n  version: v2alpha1\n  name: ciliumbgpadvertisements.cilium.io\n
        \ displayName: Cilium BGP Advertisement\n  description: |\n    CiliumBGPAdvertisement
        is used to define source of BGP advertisement as well as BGP attributes \n
        \   to be advertised with those prefixes.\n- kind: CiliumBGPNodeConfig\n  version:
        v2alpha1\n  name: ciliumbgpnodeconfigs.cilium.io\n  displayName: Cilium BGP
        Node Config\n  description: |\n    CiliumBGPNodeConfig is read only node specific
        BGP configuration. It is constructed by Cilium operator.\n    It will also
        contain node local BGP state information.\n- kind: CiliumBGPNodeConfigOverride\n
        \ version: v2alpha1\n  name: ciliumbgpnodeconfigoverrides.cilium.io\n  displayName:
        Cilium BGP Node Config Override\n  description: |\n    CiliumBGPNodeConfigOverride
        can be used to override node specific BGP configuration.\n- kind: CiliumLoadBalancerIPPool\n
        \ version: v2\n  name: ciliumloadbalancerippools.cilium.io\n  displayName:
        Cilium Load Balancer IP Pool\n  description: |\n    Defining a Cilium Load
        Balancer IP Pool instructs Cilium to assign IPs to LoadBalancer Services.\n-
        kind: CiliumCIDRGroup\n  version: v2alpha1\n  name: ciliumcidrgroups.cilium.io\n
        \ displayName: Cilium CIDR Group\n  description: |\n    CiliumCIDRGroup is
        a list of CIDRs that can be referenced as a single entity from CiliumNetworkPolicies.\n-
        kind: CiliumL2AnnouncementPolicy\n  version: v2alpha1\n  name: ciliuml2announcementpolicies.cilium.io\n
        \ displayName: Cilium L2 Announcement Policy\n  description: |\n    CiliumL2AnnouncementPolicy
        is a policy which determines which service IPs will be announced to\n    the
        local area network, by which nodes, and via which interfaces.\n- kind: CiliumPodIPPool\n
        \ version: v2alpha1\n  name: ciliumpodippools.cilium.io\n  displayName: Cilium
        Pod IP Pool\n  description: |\n    CiliumPodIPPool defines an IP pool that
        can be used for pooled IPAM (i.e. the multi-pool IPAM mode).\n- kind: CiliumGatewayClassConfig\n
        \ version: v2alpha1\n  name: ciliumgatewayclassconfigs.cilium.io\n  displayName:
        Cilium Gateway Class Config\n  description: |\n    CiliumGatewayClassConfig
        defines a configuration for Gateway API GatewayClass.\n- kind: CiliumDatapathPlugin\n
        \ version: v2alpha1\n  name: ciliumdatapathplugins.cilium.io\n  displayName:
        Cilium Datapath Plugin\n  description: |\n    CiliumDatapathPlugin is a plugin
        that extends datapath functionality.\n"
    apiVersion: v2
    appVersion: 1.20.1
    created: "2026-09-01T00:39:07.865502655+03:00"
    description: eBPF-based Networking, Security, and Observability
    digest: 06210eef7c23d15f7699c79e2fe3a1ec9c389024c5c5c006ea04022d322449a2
    home: https://cilium.io/
    icon: https://cdn.jsdelivr.net/gh/cilium/cilium@main/Documentation/images/logo-solo.svg
    keywords:
    - BPF
    - eBPF
    - Kubernetes
    - Networking
    - Security
    - Observability
    - Troubleshooting
    kubeVersion: '>= 1.21.0-0'
    name: cilium
    sources:
    - https://github.com/cilium/cilium
    urls:
    - http://10.6.0.1:8080/cilium-1.20.1.tgz
    version: 1.20.1
  harbor:
  - apiVersion: v1
    appVersion: 2.15.2
    created: "2026-09-01T00:39:07.867422758+03:00"
    description: An open source trusted cloud native registry that stores, signs,
      and scans content
    digest: 36d8eeb41b4df1aeff18c9af7709110a2fac2194b491d37957822b3359cd5e9a
    home: https://goharbor.io
    icon: https://raw.githubusercontent.com/goharbor/website/main/static/img/logos/harbor-icon-color.png
    keywords:
    - docker
    - registry
    - harbor
    maintainers:
    - email: yan-yw.wang@broadcom.com
      name: Yan Wang
    - email: stone.zhang@broadcom.com
      name: Stone Zhang
    - email: miner.yang@broadcom.com
      name: Miner Yang
    name: harbor
    sources:
    - https://github.com/goharbor/harbor
    - https://github.com/goharbor/harbor-helm
    urls:
    - http://10.6.0.1:8080/harbor-1.19.2.tgz
    version: 1.19.2
  kargo:
  - apiVersion: v2
    appVersion: v1.11.2
    created: "2026-09-01T00:39:07.874954443+03:00"
    description: Kargo
    digest: aebe9435aa79844e62ffdd221cf03ca4e665eda7f70c041c038ffd5958570feb
    maintainers:
    - email: kent@akuity.io
      name: Kent Rancourt
    - email: hoon@akuity.io
      name: Sunghoon Kang
    name: kargo
    sources:
    - https://github.com/akuity/kargo
    type: application
    urls:
    - http://10.6.0.1:8080/kargo-1.11.2.tgz
    version: 1.11.2
  - apiVersion: v2
    appVersion: v1.11.1
    created: "2026-09-01T00:39:07.87105577+03:00"
    description: Kargo
    digest: 6498207cfaf0421a0018a10c191d77b70aa5bb3f84e58ef31046c66c8b88b79b
    maintainers:
    - email: kent@akuity.io
      name: Kent Rancourt
    - email: hoon@akuity.io
      name: Sunghoon Kang
    name: kargo
    sources:
    - https://github.com/akuity/kargo
    type: application
    urls:
    - http://10.6.0.1:8080/kargo-1.11.1.tgz
    version: 1.11.1
generated: "2026-09-01T00:39:07.851519617+03:00"
