apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/clustermesh.yaml
namespace: clustermesh
commonLabels:
  app.kubernetes.io/name: hpdc-clustermesh
  app.kubernetes.io/component: multi-region
  app.kubernetes.io/part-of: hpdc-platform
