apiVersion: v1
kind: Namespace
metadata:
  name: kargo
  labels:
    app.kubernetes.io/name: kargo
    app.kubernetes.io/part-of: hpdc-platform

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kargo-dev-config
  namespace: kargo
  labels:
    app.kubernetes.io/name: kargo
    app.kubernetes.io/part-of: hpdc-platform
data:
  kargo.yaml: |
    apiVersion: kargo.akuity.io/v1beta1
    kind: Warehouse
    metadata:
      name: offline-gitops
      namespace: kargo
    spec:
      git:
        repoURL: git://git-mirror/git-mirror
        branch: main
      prune:
        maxAge: 24h
    ---
    apiVersion: kargo.akuity.io/v1beta1
    kind: Stage
    metadata:
      name: dev
      namespace: kargo
    spec:
      warehouse: offline-gitops
      promotionPolicy:
        manual: true
    ---
    apiVersion: kargo.akuity.io/v1beta1
    kind: Freight
    metadata:
      name: offline-dev
      namespace: kargo
    spec:
      commits:
        - id: offline-dev